kaltura/playkit-js-cast-sender

- src/cast-player.js
Don't create vast data structure in case of ad tag is empty.
> fix: empty vast data structure is created when no ad tag

- src/cast-ui.js
remove `CastAfterPlay` component because the chromecast button is exposed as part of the bottom bar also on ended. 
depended on https://github.com/kaltura/playkit-js-ui/pull/306
> feat(FEC-8682): end screen

- package.json
- yarn.lock
that becuase `fsevents` caused yarn to fail.
`fsevents` is a dependency of `chokidar` which is a dependency of `documentation`.
Please add a detailed description of the change, weather it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.
> chore: update the documentation version in package.json

- src/cast-playback-engine.js
- src/cast-player.js
Change the target time condition from ```>=``` to ```===```
> fix(FEC-8616): When Seeking a video, the scrubber is jumping back before the seek is applied

- src/cast-ui.js
This reverts commit 9d1c007
Use `CastAfterPlay` component because from https://github.com/kaltura/playkit-js-ui/pull/342 there is no bottom bar when casting is ended
> fix(FEC-8768): seeking back on ended doesn't work when casting

- src/cast-player.js
Listen to `CAST_STATE_CHANGED` and trigger `CAST_AVAILABLE` accordingly for UI update
> fix(FEC-8879): when no cast device is available, cast button appear but only before playback

- src/cast-player.js
Implement `isOnLiveEdge()` in cast-player.
Because the DVR isn't working properly (for now) the logic is as follows:
it always `true` unless the player is paused or `playback.startTime` is less than the `duration` (includes a threshold of `10`*), as this is the only case the DVR is working 
\* can be handled by `cast.dvrThreshold` too
Solves FEC-9618
> fix(FEC-9618): when casting, LIVE indicator is not on PC (Device which performs the casting to TV)

- src/cast-player.js
**Issue:** Chrome Android >= 73 gets `SESSION_RESUMED` in the initial session insteadof `SESSION_STARTED` so incorrectly the player starts 'resuming' flow.
**Solution:** Turn off the 'resuming' flow in Chrome Android >= 73 (meaning the playback will start from beginning also in existing session)
> fix(FEC-9157): cannot cast video on android chrome

- src/cast-player.js
Un-support Chrome-Cast on iOS chrome as it is deprecated on chrome-iOS M-70 release. See:
* https://bugs.chromium.org/p/chromium/issues/detail?id=872050
* https://github.com/googlecast/CastVideos-chrome/issues/5
Solves FEC-9148, FEC-8735
> fix(FEC-9148): ChromeCast is not available on ios mobile devices

- src/cast-ui.js
fix typo. style class `playbackGuiWWrapper` to `playbackGuiWrapper`
Solves FEC-10154
> fix(FEC-10154): cast preset is missing the font family

- src/cast-player.js
- src/cast-tracks-manager.js
* Use [`media.tracks`](https://developers.google.com/cast/docs/reference/chrome/chrome.cast.media.MediaInfo#tracks) to pass the configured captions to the receiver 
* Ignore out-of-band caption if it already exists as in-band
* Fix 'Off' track id that can be duplicated
Solves FEC-9631
Related to https://github.com/kaltura/kaltura-player-js/pull/319
> feat(FEC-9631): add support for out of band text tracks on cast sdk

- src/cast-tracks-manager.js
Avoid starting the media status interval more than once
> fix(FEC-10156): several text tracks are active in same time while casting

- src/cast-player.js
Issue: BaseRemotePlayer changed to static logger.
Solution: use in castPlayer with static logger as well.
> fix: logger changed on BaseRemotePlayer to static

- .babelrc
- .flowconfig
- package.json
- src/cast-ui.js
- src/ui-presets/ads.js
- src/ui-presets/idle.js
- src/ui-presets/index.js
- src/ui-presets/live.js
- src/ui-presets/playback.js
- yarn.lock
Issue:
1. GuiArea split to two container one contain the bottom/top bars and interactive and second the rest.
2. preset active in UI use displayName for preset changes, the name was missing so no preset change at all.
Solution:
1. add names for preset for active-preset to be able to replace presets.
2. split guiArea into 2 containers as expected on UI.
> fix(FEC-10661): Cast ui is missing

- package.json
- src/cast-player.js
move startTime to the sources config so it will take place only on the a specific source.
> feat(FEC-10686): move startTime config from playback to sources

- src/cast-player.js
Making sure KS is passed to receiver by adding KS to mediaInfo object, as part of loadMedia function.
Solves [FEC-11073](https://kaltura.atlassian.net/browse/FEC-11073)
> fix(FEC-11073): chromecast casting doesn't work on Player V7 when content is protected with KS

- src/cast-player.js
Happens since `IS_CONNECTED` listener removed on destroy of the first session, so no listener is existing to initiate the next session.
> fix(FEC-11144): Casting doesn't work if you stop it and re-initiate

- src/cast-player.js
Manage `isOnLiveEdge()` correctly by the `liveSeekableRange` object of the receiver.
related to https://github.com/kaltura/playkit-js-cast-receiver/pull/42
> feat(FEC-9236): Add support for new live Alpha in cast SDK

- .travis.yml
- src/cast-player.js
Prevent calling CastLoader.load when multiple players are loaded one after the other
Distinguish between a casting and a non-casting player
Fixes FEC-11156
Related PRs:
https://github.com/kaltura/kaltura-player-js/pull/495
https://github.com/kaltura/playkit-js-ui/pull/640
> fix(FEC-11156): cast button appears for one player only when multiple players configured on the page and casting failed

- src/cast-player.js
We set isCastInitiator=true on cast button click, and set it to false if the cast request didn't succeed or the cast menu lost focus.
However, if player A is already casting, when we click on the button in player B, we set isCastInitiator=true but we have no event to indicate that the cast request did not succeed, since a cast request can't be made at all while player A is casting, and so for player B isCastinitiator is not set to false.
When having 3+ players this can cause a situation where multiple players will have isCastInitiator set to true when a player starts casting, which will cause them all to connect to the same remote session.
To prevent this, we need to reset isCastInitiator for ALL players on disconnect.
Fixes FEC-11708.
Related PR: …
> fix(FEC-11708): V3 - cast on multiple players - if try to cast when other player are casting, the player will be disabled

- src/cast-player.js
- src/ui-presets/ads.js
- src/ui-presets/live.js
- src/ui-presets/playback.js
issue:
chromecast not working
fix:
change ui to fix ui changes
change mediaInfo to get url as chromecast api required to fix session_error
fix issues with reconnect (refresh and disconnect-connect)
> fix(SUP-39804): Chromecast Not Working
